#! /bin/bash
######## Part 1 #########
# Script parameters     #
#########################
  
# Specify the partition name from which resources will be allocated, mandatory option
#SBATCH --partition=gpu
  
# Specify the QOS, mandatory option
#SBATCH --qos=normal
  
# Specify which group you belong to, mandatory option
# This is for the accounting, so if you belong to many group,
#SBATCH --account=junogpu
  
# Specify your job name, optional option, but strongly recommand to specify some name
#SBATCH --job-name=train_1
  
# Specify how many cores you will need, default is one if not specified
#SBATCH --ntasks=1
  
# Specify the output file path of your job
# Attention!! Your afs account must have write access to the path
# Or the job will be FAILED!
#SBATCH --output=/hpcfs/juno/junogpu/fangwx/FastSim/BES/job_sub/jobs/testing_em_wgan.out
#SBATCH --error=/hpcfs/juno/junogpu/fangwx/FastSim/BES/job_sub/jobs/testing_em_wgan.err
  
# Specify memory to use, or slurm will allocate all available memory in MB
#SBATCH --mem-per-cpu=30720
#SBATCH --cpus-per-task=2  
#
# Specify how many GPU cards to use
#SBATCH --gres=gpu:v100:1 
######## Part 2 ######
# Script workload    #
######################
  
# Replace the following lines with your real workload
  
# list the allocated hosts
echo CUDA_VISIBLE_DEVICES $CUDA_VISIBLE_DEVICES
hostname
df -h
cd /hpcfs/juno/junogpu/fangwx
source /hpcfs/juno/junogpu/fangwx/setup.sh


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch100.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch100.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch100.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch100.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch100.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch101.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch101.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch101.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch101.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch101.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch102.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch102.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch102.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch102.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch102.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch103.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch103.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch103.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch103.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch103.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch104.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch104.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch104.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch104.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch104.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch105.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch105.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch105.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch105.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch105.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch106.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch106.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch106.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch106.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch106.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch107.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch107.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch107.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch107.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch107.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch108.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch108.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch108.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch108.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch108.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch109.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch109.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch109.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch109.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch109.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch110.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch110.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch110.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch110.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch110.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch111.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch111.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch111.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch111.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch111.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch112.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch112.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch112.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch112.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch112.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch113.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch113.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch113.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch113.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch113.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch114.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch114.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch114.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch114.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch114.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch115.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch115.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch115.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch115.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch115.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch116.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch116.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch116.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch116.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch116.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch117.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch117.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch117.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch117.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch117.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch118.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch118.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch118.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch118.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch118.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch119.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch119.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch119.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch119.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch119.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch120.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch120.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch120.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch120.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch120.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch121.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch121.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch121.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch121.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch121.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch122.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch122.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch122.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch122.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch122.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch123.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch123.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch123.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch123.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch123.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch124.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch124.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch124.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch124.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch124.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch125.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch125.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch125.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch125.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch125.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch126.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch126.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch126.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch126.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch126.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch127.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch127.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch127.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch127.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch127.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch128.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch128.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch128.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch128.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch128.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch129.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch129.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch129.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch129.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch129.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch130.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch130.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch130.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch130.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch130.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch131.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch131.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch131.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch131.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch131.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch132.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch132.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch132.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch132.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch132.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch133.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch133.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch133.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch133.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch133.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch134.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch134.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch134.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch134.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch134.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch135.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch135.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch135.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch135.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch135.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch136.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch136.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch136.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch136.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch136.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch137.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch137.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch137.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch137.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch137.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch138.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch138.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch138.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch138.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch138.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch139.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch139.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch139.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch139.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch139.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch140.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch140.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch140.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch140.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch140.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch141.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch141.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch141.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch141.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch141.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch142.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch142.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch142.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch142.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch142.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch143.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch143.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch143.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch143.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch143.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch144.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch144.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch144.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch144.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch144.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch145.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch145.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch145.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch145.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch145.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch146.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch146.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch146.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch146.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch146.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch147.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch147.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch147.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch147.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch147.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch148.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch148.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch148.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch148.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch148.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch149.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch149.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch149.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch149.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch149.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch150.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch150.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch150.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch150.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch150.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch151.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch151.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch151.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch151.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch151.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch152.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch152.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch152.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch152.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch152.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch153.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch153.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch153.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch153.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch153.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch154.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch154.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch154.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch154.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch154.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch155.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch155.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch155.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch155.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch155.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch156.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch156.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch156.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch156.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch156.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch157.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch157.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch157.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch157.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch157.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch158.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch158.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch158.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch158.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch158.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch159.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch159.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch159.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch159.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch159.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch160.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch160.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch160.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch160.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch160.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch161.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch161.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch161.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch161.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch161.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch162.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch162.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch162.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch162.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch162.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch163.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch163.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch163.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch163.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch163.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch164.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch164.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch164.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch164.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch164.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch165.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch165.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch165.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch165.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch165.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch166.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch166.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch166.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch166.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch166.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch167.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch167.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch167.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch167.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch167.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch168.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch168.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch168.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch168.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch168.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch169.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch169.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch169.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch169.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch169.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch170.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch170.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch170.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch170.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch170.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch171.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch171.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch171.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch171.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch171.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch172.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch172.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch172.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch172.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch172.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch173.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch173.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch173.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch173.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch173.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch174.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch174.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch174.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch174.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch174.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch175.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch175.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch175.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch175.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch175.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch176.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch176.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch176.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch176.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch176.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch177.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch177.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch177.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch177.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch177.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch178.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch178.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch178.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch178.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch178.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch179.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch179.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch179.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch179.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch179.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch180.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch180.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch180.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch180.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch180.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch181.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch181.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch181.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch181.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch181.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch182.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch182.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch182.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch182.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch182.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch183.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch183.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch183.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch183.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch183.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch184.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch184.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch184.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch184.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch184.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch185.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch185.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch185.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch185.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch185.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch186.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch186.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch186.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch186.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch186.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch187.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch187.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch187.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch187.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch187.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch188.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch188.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch188.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch188.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch188.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch189.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch189.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch189.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch189.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch189.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch190.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch190.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch190.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch190.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch190.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch191.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch191.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch191.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch191.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch191.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch192.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch192.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch192.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch192.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch192.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch193.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch193.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch193.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch193.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch193.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch194.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch194.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch194.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch194.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch194.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch195.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch195.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch195.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch195.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch195.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch196.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch196.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch196.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch196.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch196.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch197.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch197.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch197.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch197.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch197.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch198.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch198.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch198.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch198.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch198.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/generator_wgan.py --latent-size 512 --nb-events 13000 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/gen_model_em_1203w_epoch199.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/comb_model_em_1203w_epoch199.h5"   --exact-model True --exact-list '/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/exact_input_em.txt'  --output "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/Gen_em_wgan_1203w_epoch199.h5" --check-dis-real False --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/BES/params/gan/dis_model_em_1203w_epoch199.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/BES/data/Z_merged/single_em/mc_Hit_Barrel_em_test_zcut.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/BES/generator/" --name_pb "model_em_wgan_1203w_epoch199.pb" --SavedModel False 

